name: syncToGitee
on:
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/MonkeyB0ss'
          dst: 'gitee/MonkeyBoss'
          dst_key: ${{ secrets.GITHUBTOGITEE }}
          dst_token: ${{ secrets.GITEETOKEN }}
          static_list: 'Blog'
          force_update: true
          debug: true
